// Listado de países + indicativo telefónico para el campo "Sede / país" del
// formulario de la landing (punto 12.1 + ajuste "ábrelo a todos los
// países"). Al cambiar el país, LeadForm.tsx reemplaza el prefijo del campo
// WhatsApp por el dialCode correspondiente, sin borrar lo que la persona ya
// haya escrito después del indicativo.
export type Country = { name: string; dialCode: string };

export const COUNTRIES: Country[] = [
  { name: 'Colombia', dialCode: '+57' },
  { name: 'Afganistán', dialCode: '+93' },
  { name: 'Alemania', dialCode: '+49' },
  { name: 'Andorra', dialCode: '+376' },
  { name: 'Angola', dialCode: '+244' },
  { name: 'Arabia Saudita', dialCode: '+966' },
  { name: 'Argelia', dialCode: '+213' },
  { name: 'Argentina', dialCode: '+54' },
  { name: 'Armenia', dialCode: '+374' },
  { name: 'Australia', dialCode: '+61' },
  { name: 'Austria', dialCode: '+43' },
  { name: 'Azerbaiyán', dialCode: '+994' },
  { name: 'Bahamas', dialCode: '+1242' },
  { name: 'Bahréin', dialCode: '+973' },
  { name: 'Bangladés', dialCode: '+880' },
  { name: 'Barbados', dialCode: '+1246' },
  { name: 'Bélgica', dialCode: '+32' },
  { name: 'Belice', dialCode: '+501' },
  { name: 'Benín', dialCode: '+229' },
  { name: 'Bielorrusia', dialCode: '+375' },
  { name: 'Bolivia', dialCode: '+591' },
  { name: 'Bosnia y Herzegovina', dialCode: '+387' },
  { name: 'Botsuana', dialCode: '+267' },
  { name: 'Brasil', dialCode: '+55' },
  { name: 'Brunéi', dialCode: '+673' },
  { name: 'Bulgaria', dialCode: '+359' },
  { name: 'Burkina Faso', dialCode: '+226' },
  { name: 'Burundi', dialCode: '+257' },
  { name: 'Bután', dialCode: '+975' },
  { name: 'Cabo Verde', dialCode: '+238' },
  { name: 'Camboya', dialCode: '+855' },
  { name: 'Camerún', dialCode: '+237' },
  { name: 'Canadá', dialCode: '+1' },
  { name: 'Catar', dialCode: '+974' },
  { name: 'Chad', dialCode: '+235' },
  { name: 'Chile', dialCode: '+56' },
  { name: 'China', dialCode: '+86' },
  { name: 'Chipre', dialCode: '+357' },
  { name: 'Ciudad del Vaticano', dialCode: '+379' },
  { name: 'Comoras', dialCode: '+269' },
  { name: 'Corea del Norte', dialCode: '+850' },
  { name: 'Corea del Sur', dialCode: '+82' },
  { name: 'Costa de Marfil', dialCode: '+225' },
  { name: 'Costa Rica', dialCode: '+506' },
  { name: 'Croacia', dialCode: '+385' },
  { name: 'Cuba', dialCode: '+53' },
  { name: 'Dinamarca', dialCode: '+45' },
  { name: 'Dominica', dialCode: '+1767' },
  { name: 'Ecuador', dialCode: '+593' },
  { name: 'Egipto', dialCode: '+20' },
  { name: 'El Salvador', dialCode: '+503' },
  { name: 'Emiratos Árabes Unidos', dialCode: '+971' },
  { name: 'Eritrea', dialCode: '+291' },
  { name: 'Eslovaquia', dialCode: '+421' },
  { name: 'Eslovenia', dialCode: '+386' },
  { name: 'España', dialCode: '+34' },
  { name: 'Estados Unidos', dialCode: '+1' },
  { name: 'Estonia', dialCode: '+372' },
  { name: 'Etiopía', dialCode: '+251' },
  { name: 'Filipinas', dialCode: '+63' },
  { name: 'Finlandia', dialCode: '+358' },
  { name: 'Fiyi', dialCode: '+679' },
  { name: 'Francia', dialCode: '+33' },
  { name: 'Gabón', dialCode: '+241' },
  { name: 'Gambia', dialCode: '+220' },
  { name: 'Georgia', dialCode: '+995' },
  { name: 'Ghana', dialCode: '+233' },
  { name: 'Granada', dialCode: '+1473' },
  { name: 'Grecia', dialCode: '+30' },
  { name: 'Guatemala', dialCode: '+502' },
  { name: 'Guyana', dialCode: '+592' },
  { name: 'Guinea', dialCode: '+224' },
  { name: 'Guinea-Bisáu', dialCode: '+245' },
  { name: 'Guinea Ecuatorial', dialCode: '+240' },
  { name: 'Haití', dialCode: '+509' },
  { name: 'Honduras', dialCode: '+504' },
  { name: 'Hungría', dialCode: '+36' },
  { name: 'India', dialCode: '+91' },
  { name: 'Indonesia', dialCode: '+62' },
  { name: 'Irak', dialCode: '+964' },
  { name: 'Irán', dialCode: '+98' },
  { name: 'Irlanda', dialCode: '+353' },
  { name: 'Islandia', dialCode: '+354' },
  { name: 'Islas Marshall', dialCode: '+692' },
  { name: 'Islas Salomón', dialCode: '+677' },
  { name: 'Israel', dialCode: '+972' },
  { name: 'Italia', dialCode: '+39' },
  { name: 'Jamaica', dialCode: '+1876' },
  { name: 'Japón', dialCode: '+81' },
  { name: 'Jordania', dialCode: '+962' },
  { name: 'Kazajistán', dialCode: '+7' },
  { name: 'Kenia', dialCode: '+254' },
  { name: 'Kirguistán', dialCode: '+996' },
  { name: 'Kiribati', dialCode: '+686' },
  { name: 'Kuwait', dialCode: '+965' },
  { name: 'Laos', dialCode: '+856' },
  { name: 'Lesoto', dialCode: '+266' },
  { name: 'Letonia', dialCode: '+371' },
  { name: 'Líbano', dialCode: '+961' },
  { name: 'Liberia', dialCode: '+231' },
  { name: 'Libia', dialCode: '+218' },
  { name: 'Liechtenstein', dialCode: '+423' },
  { name: 'Lituania', dialCode: '+370' },
  { name: 'Luxemburgo', dialCode: '+352' },
  { name: 'Madagascar', dialCode: '+261' },
  { name: 'Malasia', dialCode: '+60' },
  { name: 'Malaui', dialCode: '+265' },
  { name: 'Maldivas', dialCode: '+960' },
  { name: 'Malí', dialCode: '+223' },
  { name: 'Malta', dialCode: '+356' },
  { name: 'Marruecos', dialCode: '+212' },
  { name: 'Mauricio', dialCode: '+230' },
  { name: 'Mauritania', dialCode: '+222' },
  { name: 'México', dialCode: '+52' },
  { name: 'Micronesia', dialCode: '+691' },
  { name: 'Moldavia', dialCode: '+373' },
  { name: 'Mónaco', dialCode: '+377' },
  { name: 'Mongolia', dialCode: '+976' },
  { name: 'Montenegro', dialCode: '+382' },
  { name: 'Mozambique', dialCode: '+258' },
  { name: 'Namibia', dialCode: '+264' },
  { name: 'Nauru', dialCode: '+674' },
  { name: 'Nepal', dialCode: '+977' },
  { name: 'Nicaragua', dialCode: '+505' },
  { name: 'Níger', dialCode: '+227' },
  { name: 'Nigeria', dialCode: '+234' },
  { name: 'Noruega', dialCode: '+47' },
  { name: 'Nueva Zelanda', dialCode: '+64' },
  { name: 'Omán', dialCode: '+968' },
  { name: 'Países Bajos', dialCode: '+31' },
  { name: 'Pakistán', dialCode: '+92' },
  { name: 'Palaos', dialCode: '+680' },
  { name: 'Panamá', dialCode: '+507' },
  { name: 'Papúa Nueva Guinea', dialCode: '+675' },
  { name: 'Paraguay', dialCode: '+595' },
  { name: 'Perú', dialCode: '+51' },
  { name: 'Polonia', dialCode: '+48' },
  { name: 'Portugal', dialCode: '+351' },
  { name: 'Reino Unido', dialCode: '+44' },
  { name: 'República Centroafricana', dialCode: '+236' },
  { name: 'República Checa', dialCode: '+420' },
  { name: 'República del Congo', dialCode: '+242' },
  { name: 'República Democrática del Congo', dialCode: '+243' },
  { name: 'República Dominicana', dialCode: '+1809' },
  { name: 'Ruanda', dialCode: '+250' },
  { name: 'Rumanía', dialCode: '+40' },
  { name: 'Rusia', dialCode: '+7' },
  { name: 'Samoa', dialCode: '+685' },
  { name: 'San Cristóbal y Nieves', dialCode: '+1869' },
  { name: 'San Marino', dialCode: '+378' },
  { name: 'San Vicente y las Granadinas', dialCode: '+1784' },
  { name: 'Santa Lucía', dialCode: '+1758' },
  { name: 'Santo Tomé y Príncipe', dialCode: '+239' },
  { name: 'Senegal', dialCode: '+221' },
  { name: 'Serbia', dialCode: '+381' },
  { name: 'Seychelles', dialCode: '+248' },
  { name: 'Sierra Leona', dialCode: '+232' },
  { name: 'Singapur', dialCode: '+65' },
  { name: 'Siria', dialCode: '+963' },
  { name: 'Somalia', dialCode: '+252' },
  { name: 'Sri Lanka', dialCode: '+94' },
  { name: 'Suazilandia', dialCode: '+268' },
  { name: 'Sudáfrica', dialCode: '+27' },
  { name: 'Sudán', dialCode: '+249' },
  { name: 'Sudán del Sur', dialCode: '+211' },
  { name: 'Suecia', dialCode: '+46' },
  { name: 'Suiza', dialCode: '+41' },
  { name: 'Surinam', dialCode: '+597' },
  { name: 'Tailandia', dialCode: '+66' },
  { name: 'Tanzania', dialCode: '+255' },
  { name: 'Tayikistán', dialCode: '+992' },
  { name: 'Timor Oriental', dialCode: '+670' },
  { name: 'Togo', dialCode: '+228' },
  { name: 'Tonga', dialCode: '+676' },
  { name: 'Trinidad y Tobago', dialCode: '+1868' },
  { name: 'Túnez', dialCode: '+216' },
  { name: 'Turkmenistán', dialCode: '+993' },
  { name: 'Turquía', dialCode: '+90' },
  { name: 'Tuvalu', dialCode: '+688' },
  { name: 'Ucrania', dialCode: '+380' },
  { name: 'Uganda', dialCode: '+256' },
  { name: 'Uruguay', dialCode: '+598' },
  { name: 'Uzbekistán', dialCode: '+998' },
  { name: 'Vanuatu', dialCode: '+678' },
  { name: 'Venezuela', dialCode: '+58' },
  { name: 'Vietnam', dialCode: '+84' },
  { name: 'Yemen', dialCode: '+967' },
  { name: 'Yibuti', dialCode: '+253' },
  { name: 'Zambia', dialCode: '+260' },
  { name: 'Zimbabue', dialCode: '+263' },
];
